"""r11 gfx-diff 이펙트: nn::vfx 방향 난수표 생성 0x7100827d04 원본 실행(unicorn).

DAT_71057d52f0 = 512개 (2u-1) 벡터(xyz, w=0), DAT_71057d52f8 = 그 정규화(frsqrte+2회 Newton, 0 길이는 0).
형상0 방향(dir = T52f8[E+0xBA++ & 0x1ff] * E+0x7CC)과 positionRandom(같은 표·같은 카운터)이 쓴다(0x710081e3e4).
할당기(param_1 vtable+0x10)만 스텁(힙 포인터 반환). memset은 원본 PLT 대신 스텁.
출력: web/games/splatoon3/client/fx/vfx_random_table.ts, tests/fixtures/r11_fx_tables.json
"""
import json, struct
from unicorn import UC_HOOK_CODE
from unicorn.arm64_const import *
from r7_fx_transform_emu import VM, ROOT, HEAP

FN = 0x7100827d04
ALLOC = 0x30000800  # inside END page mapped by VM


def main():
    vm = VM(); m = vm.mu
    obj, vt = HEAP + 0x80000, HEAP + 0x80100
    vm.q(obj, vt); vm.q(vt + 0x10, ALLOC)
    pool = [HEAP + 0x40000, HEAP + 0x60000]
    calls = []

    def hook(mu, addr, size, ud):
        if addr == ALLOC:
            p = pool[len(calls)]; calls.append(p)
            mu.mem_write(p, bytes(0x2000))
            mu.reg_write(UC_ARM64_REG_X0, p)
            mu.reg_write(UC_ARM64_REG_PC, mu.reg_read(UC_ARM64_REG_LR))
    m.hook_add(UC_HOOK_CODE, hook, begin=ALLOC, end=ALLOC + 4)
    # memset PLT: emulate (x0, w1, x2)
    memset_calls = []
    def find_memset():
        import capstone
        md = capstone.Cs(capstone.CS_ARCH_ARM64, capstone.CS_MODE_ARM); md.detail = True
        code = bytes(m.mem_read(FN, 0x200))
        return [i.operands[0].imm for i in md.disasm(code, FN) if i.mnemonic == 'bl']
    targets = set(find_memset())
    def hook_bl(mu, addr, size, ud):
        if addr in targets:
            x0 = mu.reg_read(UC_ARM64_REG_X0); n = mu.reg_read(UC_ARM64_REG_X2); v = mu.reg_read(UC_ARM64_REG_X1) & 0xff
            mu.mem_write(x0, bytes([v]) * n); memset_calls.append((hex(addr), n))
            mu.reg_write(UC_ARM64_REG_PC, mu.reg_read(UC_ARM64_REG_LR))
    for t in targets:
        m.hook_add(UC_HOOK_CODE, hook_bl, begin=t, end=t + 4)
    vm.call(FN, obj)
    raw0 = bytes(m.mem_read(pool[0], 0x2000)); raw1 = bytes(m.mem_read(pool[1], 0x2000))
    t0 = [list(struct.unpack_from('<4f', raw0, i * 16)) for i in range(512)]
    t1 = [list(struct.unpack_from('<4f', raw1, i * 16)) for i in range(512)]
    g0 = struct.unpack('<Q', bytes(m.mem_read(0x71057d52f0, 8)))[0]; g1 = struct.unpack('<Q', bytes(m.mem_read(0x71057d52f8, 8)))[0]
    assert (g0, g1) == tuple(pool), (hex(g0), hex(g1))
    lens = [sum(x * x for x in v[:3]) ** .5 for v in t1]
    out = {"function": hex(FN), "allocStub": True, "memsetStub": sorted(set(c[0] for c in memset_calls)),
           "table52f0": t0, "table52f8": t1, "unitLenMin": min(lens), "unitLenMax": max(lens)}
    (ROOT / 'web/games/splatoon3/tests/fixtures/r11_fx_tables.json').write_text(json.dumps(out), encoding='utf8')
    hexes = ','.join(f'0x{struct.unpack("<I", struct.pack("<f", x))[0]:08x}' for v in t1 for x in v[:3])
    ts = ('// Generated by web/tools/r11_gfx_fx_tables.py from original 0x7100827d04 (unicorn). Do not edit.\n'
          '// nn::vfx DAT_71057d52f8: 512 unit vectors (xyz). Shape0 direction and positionRandom index it with E+0xBA++.\n'
          f'const BITS = new Uint32Array([{hexes}]);\n'
          'export const VFX_DIR_TABLE = new Float32Array(BITS.buffer);\n')
    (ROOT / 'web/games/splatoon3/client/fx/vfx_random_table.ts').write_text(ts, encoding='utf8')
    print(json.dumps({k: v for k, v in out.items() if not k.startswith('table')}), t1[:3])


if __name__ == '__main__':
    main()
